### ISSUE TITLE
Archive missing September and October 1978

### ISSUE THREAD

**Issue by dgarcia-eu** [NYTimes/public_api_specs#42]
Dear NYTimes API developers,

The archive API returns zero hits for the months of September and October 1978. Below I paste the calls and responses that I got, which work normally for any other month in the archive:

Call: https://api.nytimes.com/svc/archive/v1/1978/10.json
Response: {"copyright":"Copyright (c) 2013 The New York Times Company.  All Rights Reserved.","response":{"meta":{"hits":0},"docs":[]}}

Call: https://api.nytimes.com/svc/archive/v1/1978/9.json
Response:{"copyright":"Copyright (c) 2013 The New York Times Company.  All Rights Reserved.","response":{"meta":{"hits":0},"docs":[]}}

Is the NYT archive really empty those two months or is there any issue I'm missing?

Best regards,
David Garcia

**Comment by nyt-hughmandeville** [comment]
From Wikipedia
https://en.m.wikipedia.org/wiki/The_New_York_Times

Because of holidays, no editions were printed on November 23, 1851; January
2, 1852; July 4, 1852; January 2, 1853; and January 1, 1854.[179]
<https://en.m.wikipedia.org/wiki/The_New_York_Times#cite_note-reprint_disclaimers-181>

Because of strikes <https://en.m.wikipedia.org/wiki/Strike_action>, the
regular edition of The New York Times was not printed during the following
periods:[180]
<https://en.m.wikipedia.org/wiki/The_New_York_Times#cite_note-182>

   - December 9, 1962, to March 31, 1963. Only a western edition was
   printed because of the 1962–63 New York City newspaper strike
   <https://en.m.wikipedia.org/wiki/1962%E2%80%9363_New_York_City_newspaper_strike>
   .
   - September 17, 1965, to October 10, 1965. An international edition was
   printed, and a weekend edition replaced the Saturday and Sunday papers.
   - August 10, 1978, to November 5, 1978. A multi-union strike shut down
   the three major New York City newspapers. No editions of The New York
   Times were printed.[179]
   <https://en.m.wikipedia.org/wiki/The_New_York_Times#cite_note-reprint_disclaimers-181>
Two
   months into the strike, a parody of The New York Times called Not The
   New York Timeswas distributed in the city, with contributors such as Carl
   Bernstein <https://en.m.wikipedia.org/wiki/Carl_Bernstein>, Christopher
   Cerf
   <https://en.m.wikipedia.org/wiki/Christopher_Cerf_(musician_and_television_producer)>
   , Tony Hendra <https://en.m.wikipedia.org/wiki/Tony_Hendra> and George
   Plimpton <https://en.m.wikipedia.org/wiki/George_Plimpton>.[181]
   <https://en.m.wikipedia.org/wiki/The_New_York_Times#cite_note-183>[182]
   <https://en.m.wikipedia.org/wiki/The_New_York_Times#cite_note-184>


On Apr 24, 2018, at 4:13 AM, David Garcia <notifications@github.com> wrote:

Dear NYTimes API developers,

The archive API returns zero hits for the months of September and October
1978. Below I paste the calls and responses that I got, which work normally
for any other month in the archive:

Call: https://api.nytimes.com/svc/archive/v1/1978/10.json
Response: {"copyright":"Copyright (c) 2013 The New York Times Company. All
Rights Reserved.","response":{"meta":{"hits":0},"docs":[]}}

Call: https://api.nytimes.com/svc/archive/v1/1978/9.json
Response:{"copyright":"Copyright (c) 2013 The New York Times Company. All
Rights Reserved.","response":{"meta":{"hits":0},"docs":[]}}

Is the NYT archive really empty those two months or is there any issue I'm
missing?

Best regards,
David Garcia

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NYTimes/public_api_specs/issues/42>, or mute the thread

**Comment by dgarcia-eu** [comment]
That was quick and tremendously useful, thanks a lot!
Best,
David
