### ISSUE TITLE
Community API Error

### ISSUE THREAD

**Issue by marwie** [NYTimes/public_api_specs#6]
http://developer.nytimes.com/community_api_v3.json#/Console/GET/user-content/url.json

I try to access the Community API but I only get the following result:

Status Code 500: Internal Server Error 
An unexpected error occurred

I'm using my API Key

This is one of the URLs I was trying to work with:
http://www.nytimes.com/2016/05/29/magazine/behind-the-barricades-of-turkeys-hidden-war.html?rref=collection%2Fsectioncollection%2Fmagazine

**Comment by marwie** [comment]
example request from documentation page (replace api key with your own): 
#http://api.nytimes.com/svc/community/v3/user-content/url.json?api-key=[MYKEY]&url=http%3A%2F%2Fwww.nytimes.com%2F2008%2F01%2F02%2Fopinion%2F02diamond.html

can anyone confirm this error? and/or provide a solution?

**Comment by scottefein** [comment]
Can confirm there's an issue with that API currently. Working on a fix. Will let you know when we have an update.

**Comment by MixedMessages** [comment]
Hey @marwie, is this still an ongoing issue for you?

**Comment by marwie** [comment]
Hi, thanks but I havent tried since July as the project is already finished so it's not an issue for me anymore. 

It seems to work now (judging by the url I posted on 29th May) but doesn't require an api key anymore - Dont know if that's intended?

**Comment by devikaraj1** [comment]
Hi,
I'm a student and as a part of my project I'm trying to do an article search using NYTimes API. Earlier(2 months back) I was able to read from the JSON result obtained for a particular time period. But now I'm getting error 429,which i understand is due to Cross domain resource sharing issues. I'm using javascript and xmlhttprequest to obtain the number of articles published in a particular time frame. Could you suggest a way to overcome these issues?

Thanks,
Devika

**Comment by scottefein** [comment]
429 is due to you being over your rate limit. http://developer.nytimes.com/faq#9
